import type { SkillDefinition } from "@/lib/types/skills";

export const skillRegistry: SkillDefinition[] = [
  {
    id: "skill-summarise-regulation",
    name: "Summarise Regulation",
    description: "Condense regulatory updates into executive-ready summaries.",
    input: "Regulation document or knowledge item IDs",
    output: "Structured summary with key changes and compliance actions",
    enabled: true,
  },
  {
    id: "skill-compare-documents",
    name: "Compare Documents",
    description: "Compare two or more documents for differences and alignment gaps.",
    input: "Document IDs or text payloads to compare",
    output: "Comparison matrix with highlighted differences",
    enabled: true,
  },
  {
    id: "skill-executive-brief",
    name: "Executive Brief",
    description: "Generate a daily executive brief from knowledge, memory, and tasks.",
    input: "Knowledge, memory, research, calendar, and task context",
    output: "Executive brief with priorities, risks, and recommended focus",
    enabled: true,
  },
  {
    id: "skill-extract-risks",
    name: "Extract Risks",
    description: "Identify risks from proposals, reports, and regulatory updates.",
    input: "Document or knowledge item content",
    output: "Ranked risk list with severity and mitigation notes",
    enabled: true,
  },
  {
    id: "skill-extract-deadlines",
    name: "Extract Deadlines",
    description: "Surface deadlines and compliance dates from documents and calendar.",
    input: "Documents, calendar events, and task lists",
    output: "Deadline register sorted by urgency",
    enabled: true,
  },
  {
    id: "skill-generate-proposal",
    name: "Generate Proposal",
    description: "Draft proposal sections from scope notes and project memory.",
    input: "Project scope, pricing assumptions, and related knowledge",
    output: "Proposal draft with executive summary and scope sections",
    enabled: false,
  },
  {
    id: "skill-generate-presentation",
    name: "Generate Presentation",
    description: "Create presentation outlines from briefs and training content.",
    input: "Brief content, topic, and audience profile",
    output: "Slide outline with speaker notes",
    enabled: false,
  },
  {
    id: "skill-meeting-summary",
    name: "Create Meeting Summary",
    description: "Summarise meeting notes into decisions, actions, and follow-ups.",
    input: "Meeting transcript or notes",
    output: "Summary with decisions, owners, and next steps",
    enabled: true,
  },
  {
    id: "skill-detect-regulation-changes",
    name: "Detect Regulation Changes",
    description: "Monitor trusted sources for regulatory changes relevant to your operations.",
    input: "Trusted source IDs and monitoring window",
    output: "Change log with affected areas and recommended actions",
    enabled: true,
  },
  {
    id: "skill-suggest-priorities",
    name: "Suggest Priorities",
    description: "Recommend top priorities based on deadlines, risks, and opportunities.",
    input: "Tasks, calendar, memory, and research queue",
    output: "Ranked priority list with rationale",
    enabled: true,
  },
];
