import type { TrustedSourceDefinition } from "@/lib/types/sources";

export const trustedSources: TrustedSourceDefinition[] = [
  {
    id: "src-icao",
    name: "ICAO",
    category: "Aviation",
    description: "International Civil Aviation Organization standards and safety guidance.",
    baseUrl: "https://www.icao.int",
    enabled: true,
    tags: ["ICAO", "RVSM", "CBTA"],
  },
  {
    id: "src-caam",
    name: "CAAM",
    category: "Aviation",
    description: "Civil Aviation Authority of Malaysia regulations and circulars.",
    baseUrl: "https://www.caam.gov.my",
    enabled: true,
    tags: ["CAAM", "CBTA"],
  },
  {
    id: "src-faa",
    name: "FAA",
    category: "Aviation",
    description: "US Federal Aviation Administration regulations and advisories.",
    baseUrl: "https://www.faa.gov",
    enabled: true,
    tags: ["CBTA", "RVSM"],
  },
  {
    id: "src-easa",
    name: "EASA",
    category: "Aviation",
    description: "European Union Aviation Safety Agency rules and compliance updates.",
    baseUrl: "https://www.easa.europa.eu",
    enabled: true,
    tags: ["RVSM", "CBTA"],
  },
  {
    id: "src-iata",
    name: "IATA",
    category: "Aviation",
    description: "International Air Transport Association operations and training trends.",
    baseUrl: "https://www.iata.org",
    enabled: true,
    tags: ["CBTA"],
  },
  {
    id: "src-boeing",
    name: "Boeing",
    category: "Aviation",
    description: "Boeing technical bulletins, fleet updates, and industry insights.",
    baseUrl: "https://www.boeing.com",
    enabled: true,
    tags: ["RVSM"],
  },
  {
    id: "src-airbus",
    name: "Airbus",
    category: "Aviation",
    description: "Airbus safety information, fleet updates, and technical publications.",
    baseUrl: "https://www.airbus.com",
    enabled: true,
    tags: ["RVSM"],
  },
  {
    id: "src-cidb",
    name: "CIDB",
    category: "Construction",
    description: "Construction Industry Development Board Malaysia standards and compliance.",
    baseUrl: "https://www.cidb.gov.my",
    enabled: true,
    tags: ["Proposal", "Steelworks"],
  },
  {
    id: "src-hbr",
    name: "Harvard Business Review",
    category: "Leadership",
    description: "Executive decision-making and organisational strategy.",
    baseUrl: "https://hbr.org",
    enabled: true,
    tags: ["Leadership"],
  },
  {
    id: "src-mckinsey",
    name: "McKinsey",
    category: "Strategy",
    description: "Industry analysis and transformation frameworks.",
    baseUrl: "https://www.mckinsey.com",
    enabled: true,
    tags: ["Leadership", "Finance"],
  },
  {
    id: "src-world-bank",
    name: "World Bank",
    category: "Economics",
    description: "Global economic outlook and infrastructure investment signals.",
    baseUrl: "https://www.worldbank.org",
    enabled: true,
    tags: ["Finance"],
  },
  {
    id: "src-oecd",
    name: "OECD",
    category: "Policy",
    description: "Policy research, economic indicators, and regulatory trends.",
    baseUrl: "https://www.oecd.org",
    enabled: true,
    tags: ["Finance", "Leadership"],
  },
  {
    id: "src-who",
    name: "WHO",
    category: "Health",
    description: "World Health Organization guidance and operational health standards.",
    baseUrl: "https://www.who.int",
    enabled: true,
    tags: [],
  },
  {
    id: "src-mit",
    name: "MIT",
    category: "Research",
    description: "MIT research publications and technology innovation signals.",
    baseUrl: "https://www.mit.edu",
    enabled: true,
    tags: [],
  },
  {
    id: "src-openai",
    name: "OpenAI",
    category: "AI",
    description: "OpenAI product updates, research, and AI capability releases.",
    baseUrl: "https://openai.com",
    enabled: true,
    tags: [],
  },
  {
    id: "src-microsoft-learn",
    name: "Microsoft Learn",
    category: "Technology",
    description: "Microsoft platform documentation and learning pathways.",
    baseUrl: "https://learn.microsoft.com",
    enabled: true,
    tags: [],
  },
  {
    id: "src-google-ai",
    name: "Google AI",
    category: "AI",
    description: "Google AI research, models, and developer guidance.",
    baseUrl: "https://ai.google",
    enabled: true,
    tags: [],
  },
];
